- src/CMakeLists.txt
The generated file was a dylib. We had to change the type to a MacOSX bundle
(see https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/MachOTopics/1-Articles/building_files.html#//apple_ref/doc/uid/TP40001828-97030).
The extension need to be .bundle in order for Ruby to load the ressource.
> Fix Ruby bindings on OSX.

- src/CMakeLists.txt
Honor DESTDIR environment variable during installation, see also #54 and below:
failed to create symbolic link '/usr/bin/dislocker': Permission denied
failed to create symbolic link '/usr/share/man/man1/dislocker.1.gz': Permission denied
> Honor DESTDIR environment variable during installation

- src/metadata/fvek.c
- src/metadata/vmk.c
Include limits.h to avoid "error: 'UINT_MAX' undeclared" during build
> Include limits.h to avoid "error: 'UINT_MAX' undeclared" during build

- include/dislocker/dislocker.h
- include/dislocker/encryption/decrypt.h
Avoid "error: expected declaration specifiers or '...' before 'off_t'" build failure on RHEL 5
> Avoid "error: expected declaration specifiers or '...' before 'off_t'

- include/dislocker/metadata/datums.h
- include/dislocker/metadata/metadata.priv.h
Replace C++11 syntax by something that GCC 4.1 on RHEL 5 is able to understand. Btw, why C++11 syntax in a *.c file?
> Replace C++11 syntax by something that GCC 4.1 compatible

- INSTALL.md
Update _INSTALL.md_  to more accurately reflect the development library install strings that will be needed with the different versions of Ubuntu and Debian based distributions.
> Small update to install document for Ubuntu and Debian

- src/CMakeLists.txt
When cmake is run outside of .`/src`, the path to the manpages source will be incorrect, so `PROJECT_SOURCE_DIR` or some other variable should be used in place of `..`
> non-relative man path needed for when build path is relocated

- include/dislocker/common.h
- include/dislocker/ntfs/encoding.h
- src/CMakeLists.txt
- src/accesses/user_pass/user_pass.c
- src/common.c
- src/ntfs/encoding.c
Using iconv() to convert the password from the local character set to UTF-16LE used by BitLocker.
Still a basic support, but it is working. Tested on Ubuntu 12.04, OS X 10.11 and OS X 10.7
It will try to convert from local char set to UTF-16. If conversion is not possible, then it will use the original method (adding \0 to each character).
> Support for multi-byte characters in passwords

- man/linux/dislocker-file.1
The example used the incorrect command.
> Update commando example

- include/dislocker/metadata/datums.h
- src/inouts/inouts.c
- src/metadata/datums.c
- src/metadata/metadata.c
Fixed an issue that dislocker corrupted when unlocking BitLocker drive created in Windows 10 1903.
Fixed an issue that it failed to unlock exFAT BitLocker drive created in Windows 10 1903.
> Fixed issues in Windows 10 1903 

- include/dislocker/accesses/user_pass/user_pass.h
- src/accesses/user_pass/user_pass.c
- src/inouts/inouts.c
- src/inouts/prepare.c
- src/metadata/metadata.c
2020-10-16:Fixed an issue that the decryption process got corrupted when using password to unlock a BitLocker partition which does not have a password.
Note: A BitLocker partition that does not have a password, e.g. it is encrypted via TPM instead of a password.
old
1.Get volume size directly from dis_metadata_t, which is more accurate.
2.Fixed the build error on Mac OS
3.Fixed an issue that NTFS volume size was incorrect (one sector smaller) after the drive was unlocked.
> Fixed some issues

- .travis.yml
- INSTALL.md
- cmake/FindFUSE.cmake
- src/CMakeLists.txt
- src/dislocker-fuse.c
This drops osxfuse support in favor of macFUSE. macFUSE is a newer version of osxfuse that supports the latest release of macOS, and is a rebranded version of the same project.
This also makes the build script locate libfuse more reliably by using pkg-config instead of searching in predetermined directories.
> Support the latest FUSE on macOS

- src/config.c
With ruby 3.0, build fails like:
```
/builddir/build/BUILD/dislocker-0.7.3/src/config.c: In function 'setclearkey':
/builddir/build/BUILD/dislocker-0.7.3/src/config.c:59:13: error: expected identifier or '(' before numeric constant
59 |         int true = TRUE;
```
This is because ruby 3.0 header will include <stdbool.h>, which defines
"true"/"false", ref:
https://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdbool.h.html
So using "true" as variable must be renamed.
> Fix build failure with ruby 3.0

- src/CMakeLists.txt
As mentioned in https://github.com/Aorimn/dislocker/issues/207, port the patch from https://aur.archlinux.org/packages/dislocker-noruby/ and extend it to make WITH_RUBY a tri-state ON/OFF/AUTO variable.
Similarly, allow building without FUSE support. While FUSE is essential to the main use-case of Dislocker (mounting volumes), it's still possible to use dislocker-file without FUSE.  Also, try to make a lack of FUSE fail at configure time rather than later on when compiling or linking.
> Make Ruby and FUSE libraries optional

- src/metadata/metadata.c
* Incorrect rest_size calculation
* When calculating CRC, the stored CRC part should be excluded.
> Fix reading eow informations and incorrect crc checks

- include/dislocker/metadata/metadata.h
- include/dislocker/metadata/metadata_config.h
- src/dislocker-metadata.c
- src/dislocker.c
- src/inouts/prepare.c
- src/metadata/metadata.c
Make the decrypted BitLocker volume also available as shown below.
bitlocker_information:
```
00000000  2d 46 56 45 2d 46 53 2d  26 00 02 00 01 00 01 00  |-FVE-FS-&.......|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 10 00 00 00  |................|
00000020  00 00 ea 03 00 00 00 00  00 e0 68 44 00 00 00 00  |..........hD....|
00000030  00 70 da aa 00 00 00 00  00 00 eb 03 00 00 00 00  |.p..............|
00000040  18 02 00 00 01 00 00 00  30 00 00 00 18 02 00 00  |........0.......|
```
Usage:
```bash
$ dislocker-fuse -v -r -V /dev/sdb2 -c -- /mnt/disk2
$ dd if=/mnt/disk2/dislocker-file bs=512 count=1 | hexdump -C
00000000  eb 52 90 4e 54 46 53 20  20 20 20 00 02 08 00 00  |.R.NTFS    .....|
00000010  00 00 00 00 00 f8 00 00  3f 00 ff 00 00 30 11 00  |........?....0..|
00000020  00 00 00 …
```
> Make mountable of the decrypted volume

- include/dislocker/metadata/datums.h
- src/dislocker-fuse.c
- src/metadata/datums.c
Hi, I noticed a segfault when using dislocker on fedora 36 and it seems some changed default compiler flags 
has made the runtime more sensitive to memory over/under reads. I compiled with -fsanitize=address,undefined and re-ran my tests which made it easier to spot the errors (see the individual commit messages for the sanitizer dumps).
I tested these fixes mounting an bitlocker image without it crashing but I am not familiar with this code base so I might have messed something up. 
Thanks for this project btw!
> Minor out of bounds reads and use after free fixes

- cmake/FindPolarSSL.cmake
Fixed an issue in cmake/FindPolarSSL.cmake where the system's
C compiler would be called directly without the shim to provide
access to standard system libraries. With this fix, building
on macOS no longer fails to find stdio.h ;)
> Fix for macOS build failing on Monterey (#278)

- .gitignore
- cmake/FindPolarSSL.cmake
- include/dislocker/ssl_bindings.h.in
Various patches that make this work with the latest libraries, and specifically macOS 12 Monterey.
Confirmed by running:
```
brew install --cask macfuse
xcode-select --install
export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
make .
make
sudo make install
> fix: Make compatible with macOS 12 Monterey & mbedtls 3

- src/inouts/sectors.c
- src/metadata/fvek.c
- Potential NULL dereference in sectors.c because it uses malloc() but doesn't check for NULL. Switched to dis_malloc() instead (should exit cleanly on failure), and matching dis_free()
- Fixed signed/unsigned warning in sectors.c (depending on off_t type and compiler flags)
- Fixed memory leak on failure cases in fvek.c
> fix potential NULL deref and memory leak

- .gitignore
- cmake/FindPolarSSL.cmake
- include/dislocker/ssl_bindings.h.in
Reverts Aorimn/dislocker#280 as per https://github.com/Aorimn/dislocker/issues/304
We'll need another fix that doesn't break linux builds.
> Revert "fix: Make compatible with macOS 12 Monterey & mbedtls 3"

- .gitignore
- INSTALL.md
- cmake/FindPolarSSL.cmake
- include/dislocker/ssl_bindings.h.in
Main changes:
- Dynamically locate macOS SDK
- Add support for Mbed TLS 3
Tested building in macOS 12.6.9, 13.5.1 and Ubuntu 22.04.3.
> Re-enable macOS building

- src/dislocker-find.rb.in
Method File.exists was deprecated with Ruby 2.2.0 and removed with Ruby 3.2.0 according to
https://www.reddit.com/r/ruby/comments/1196wti/psa_and_a_little_rant_fileexists_direxists/.
> Fix use of File.exists removed with Ruby 3.2.0, fixes issue #298
